import Ionicons from "@expo/vector-icons/Ionicons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Image, StyleSheet, Text, View } from "react-native";
import { useHarvest } from "@/src/presentation/harvest/useHarvests";
import { AppButton, AppCard, FeedbackState, ScreenContainer } from "@/src/ui/components";
import { tokens } from "@/src/ui/tokens";
export default function HarvestResultScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const resource = useHarvest(id); const harvest = resource.data;
  if (resource.loading) return <ScreenContainer><FeedbackState kind="loading" title="Saving your harvest" description="Preparing a few useful ideas for what comes next." /></ScreenContainer>;
  if (resource.error) return <ScreenContainer><FeedbackState kind="error" title="Your harvest could not be loaded" description={resource.error.message} actionLabel="Try again" onAction={() => void resource.reload()} /></ScreenContainer>;
  if (!harvest) return <ScreenContainer><FeedbackState kind="empty" title="Harvest not found" description="Your other harvests are available in the Private Garden." /></ScreenContainer>;
  const suggestions = harvest.record.suggestions;
  return <ScreenContainer scroll contentStyle={styles.container}>
    <View style={styles.icon}><Ionicons color={tokens.colors.stone} name="leaf" size={42} /></View><View style={styles.intro}><Text style={styles.eyebrow}>HARVEST {harvest.record.harvestNumber}</Text><Text accessibilityRole="header" style={styles.title}>You grew this.</Text><Text style={styles.body}>Your {harvest.seed.commonName} harvest is now part of your growing history.</Text></View>
    {harvest.photoUrl
      ? <View style={styles.photoFrame}><Image accessibilityLabel={`${harvest.seed.commonName} harvest`} resizeMode="cover" source={{ uri: harvest.photoUrl }} style={styles.photo} /></View>
      : <AppCard variant="nested" style={styles.noPhoto}><Ionicons color={tokens.colors.coachLabel} name="image-outline" size={36} /><View style={styles.noPhotoCopy}><Text style={styles.noPhotoTitle}>No harvest photo added</Text><Text style={styles.noPhotoBody}>This harvest is saved in your Private Garden without a photo.</Text></View></AppCard>}
    <AppCard variant="nested" style={styles.celebration}><Text style={styles.celebrationTitle}>{suggestions?.headline ?? `Fresh ${harvest.seed.commonName}, ready to enjoy`}</Text><Text style={styles.celebrationBody}>Harvested {formatDate(harvest.record.harvestedAt)}. {harvest.seed.storageGuidance}</Text></AppCard>
    <View style={styles.section}><Text style={styles.sectionTitle}>A few ways to use it</Text>{(suggestions?.ideas ?? fallbackIdeas(harvest.seed.commonName, harvest.seed.tasteProfile)).map((idea) => <AppCard key={idea.title} style={styles.idea}><Text style={styles.ideaTitle}>{idea.title}</Text><Text style={styles.body}>{idea.description}</Text></AppCard>)}</View>
    <AppButton label="View Private Garden" onPress={() => router.replace("/harvest/gallery")} /><AppButton label="Grow another seed" onPress={() => router.replace("/(tabs)/explore")} variant="oliveText" />
  </ScreenContainer>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "long", year: "numeric" }).format(new Date(value)); }
function fallbackIdeas(name: string, taste: string) { return [{ title: "Add it fresh", description: `Use your ${name} as a fresh finishing touch. ${taste}` }, { title: "Keep it simple", description: `Fold the ${name} through a sandwich, salad, or grain bowl just before serving.` }, { title: "Save some for later", description: "Follow the storage guidance above and use the most delicate leaves first." }]; }
const styles = StyleSheet.create({ container: { gap: tokens.spacing.cardGap, paddingBottom: tokens.spacing.xl }, icon: { alignItems: "center", alignSelf: "center", backgroundColor: tokens.colors.terracottaText, borderRadius: tokens.radii.card, height: 96, justifyContent: "center", width: 96, ...tokens.elevation.raisedMd }, intro: { alignItems: "center", gap: tokens.spacing.sm, marginHorizontal: tokens.spacing.md }, eyebrow: { ...tokens.typography.label, color: tokens.colors.oliveLabel }, title: { ...tokens.typography.displayLarge, color: tokens.colors.terracottaText, textAlign: "center" }, body: { ...tokens.typography.body, color: tokens.colors.ink82 }, photoFrame: { backgroundColor: tokens.colors.card, borderRadius: tokens.radii.media, padding: 6, ...tokens.elevation.raisedLg }, photo: { borderRadius: 20, height: 240, width: "100%" }, noPhoto: { alignItems: "center", flexDirection: "row", gap: tokens.spacing.md, minHeight: 128 }, noPhotoCopy: { flex: 1, gap: tokens.spacing.xs }, noPhotoTitle: { ...tokens.typography.cardTitle, color: tokens.colors.raised }, noPhotoBody: { ...tokens.typography.body, color: tokens.colors.raised }, celebration: { gap: tokens.spacing.sm }, celebrationTitle: { ...tokens.typography.cardTitle, color: tokens.colors.raised }, celebrationBody: { ...tokens.typography.body, color: tokens.colors.raised }, section: { gap: tokens.spacing.sm }, sectionTitle: { ...tokens.typography.displayMedium, color: tokens.colors.forest, marginHorizontal: tokens.spacing.md }, idea: { gap: tokens.spacing.xs }, ideaTitle: { ...tokens.typography.cardTitle, color: tokens.colors.forest } });
