import Ionicons from "@expo/vector-icons/Ionicons";
import { useRouter } from "expo-router";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { resolveSeedImage } from "@/src/presentation/content/seedImages";
import { useHarvestGallery } from "@/src/presentation/harvest/useHarvests";
import { FeedbackState, ScreenContainer } from "@/src/ui/components";
import { tokens } from "@/src/ui/tokens";
export default function PrivateGardenScreen() {
  const router = useRouter(); const resource = useHarvestGallery();
  return <ScreenContainer scroll contentStyle={styles.container}><View style={styles.header}><Pressable accessibilityLabel="Back" accessibilityRole="button" hitSlop={12} onPress={() => router.back()}><Ionicons color={tokens.colors.ink} name="arrow-back" size={tokens.layout.icon.lg} /></Pressable><Ionicons color={tokens.colors.olive} name="lock-closed-outline" size={tokens.layout.icon.md} /></View><View style={styles.intro}><Text style={styles.eyebrow}>PRIVATE TO YOU</Text><Text accessibilityRole="header" style={styles.title}>Your Garden</Text><Text style={styles.body}>A quiet record of what you have grown and harvested.</Text></View>
    {resource.loading ? <FeedbackState kind="loading" title="Opening your garden" description="Gathering your harvest history." /> : null}{resource.error ? <FeedbackState kind="error" title="Your garden is unavailable" description={resource.error.message} actionLabel="Try again" onAction={() => void resource.reload()} /> : null}{!resource.loading && !resource.error && resource.data.length === 0 ? <FeedbackState kind="empty" title="Your first harvest will live here" description="Complete a grow cycle to begin your private archive." /> : null}
    <View style={styles.grid}>{resource.data.map((item) => { const source = item.photoUrl ? { uri: item.photoUrl } : resolveSeedImage(item.seed.images); return <Pressable accessibilityRole="button" key={item.record.id} onPress={() => router.push(`/harvest/${item.record.id}`)} style={styles.card}>{source ? <Image accessibilityLabel={`${item.seed.commonName} harvest`} source={source} style={styles.image} /> : null}<View style={styles.copy}><Text style={styles.name}>{item.seed.commonName}</Text><Text style={styles.meta}>{formatDate(item.record.harvestedAt)} · Harvest {item.record.harvestNumber}</Text>{!item.photoUrl ? <Text style={styles.authored}>Seed photo</Text> : null}</View></Pressable>; })}</View></ScreenContainer>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
const styles = StyleSheet.create({ container: { gap: tokens.spacing.sectionGap, paddingBottom: tokens.spacing.xl }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginHorizontal: tokens.spacing.md, minHeight: tokens.layout.size.touchTarget }, intro: { gap: tokens.spacing.sm, marginHorizontal: tokens.spacing.md }, eyebrow: { ...tokens.typography.label, color: tokens.colors.oliveLabel }, title: { ...tokens.typography.displayLarge, color: tokens.colors.terracottaText }, body: { ...tokens.typography.body, color: tokens.colors.ink82 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: tokens.spacing.cardGap }, card: { backgroundColor: tokens.colors.card, borderRadius: tokens.radii.card, overflow: "hidden", width: "48%", ...tokens.elevation.raisedMd }, image: { aspectRatio: 1, width: "100%" }, copy: { gap: tokens.spacing.xxs, padding: tokens.spacing.sm }, name: { ...tokens.typography.cardTitle, color: tokens.colors.forest }, meta: { ...tokens.typography.caption, color: tokens.colors.ink82 }, authored: { ...tokens.typography.caption, color: tokens.colors.oliveLabel, textTransform: "uppercase" } });
