"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import { validatePublication } from "@/lib/content";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

// Draft content is deliberately open-ended because it mirrors versioned database JSON.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type JsonRecord = Record<string, any>;

const textFields = [
  ["name","Common name"],["botanical_name","Botanical name"],["slug","Slug"],["description","Description"],
  ["expected_result","Expected result"],["difficulty_label","Difficulty"],["environment_summary","Environment"],
  ["light_summary","Light"],["taste_profile","Taste profile"],["harvest_readiness","Harvest readiness"],
  ["harvest_instructions","Harvest instructions"],["storage_guidance","Storage guidance"]
] as const;

export function SeedEditor({seedId,initialSeed,initialStages,initialStatus,role}:{seedId:string;initialSeed:JsonRecord;initialStages:JsonRecord[];initialStatus:string;role:string}){
  const router=useRouter(); const supabase=createSupabaseBrowserClient();
  const [seed,setSeed]=useState(initialSeed); const [stages,setStages]=useState(initialStages); const [status,setStatus]=useState(initialStatus);
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const validation=useMemo(()=>validatePublication(seed,stages),[seed,stages]);
  function setField(key:string,value:unknown){setSeed(current=>({...current,[key]:value}));setStatus("draft")}
  function setStage(index:number,key:string,value:unknown){setStages(current=>current.map((stage,i)=>i===index?{...stage,[key]:value}:stage));setStatus("draft")}
  async function save(nextStatus=status){setBusy(true);setMessage("");const {error}=await supabase.from("seed_drafts").upsert({seed_id:seedId,seed_data:seed,stages_data:stages,status:nextStatus,validation_errors:validation.errors,updated_at:new Date().toISOString()});setBusy(false);setStatus(nextStatus);setMessage(error?.message??"Draft saved.");router.refresh();return !error}
  async function publish(){if(!validation.valid){setMessage("Fix validation errors before publishing.");return}if(!await save("ready"))return;setBusy(true);const {data,error}=await supabase.rpc("publish_seed_draft",{p_seed_id:seedId});setBusy(false);setMessage(error?.message??`Published version ${data}.`);if(!error){setStatus("published");router.refresh()}}
  async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);const extension=file.name.split(".").pop()?.toLowerCase()??"jpg";const path=`${seedId}/${crypto.randomUUID()}.${extension}`;const {error}=await supabase.storage.from("seed-content").upload(path,file,{contentType:file.type});if(error){setMessage(error.message);setBusy(false);return}const {data}=supabase.storage.from("seed-content").getPublicUrl(path);setField("images",[...(Array.isArray(seed.images)?seed.images:[]),{kind:"remote",url:data.publicUrl}]);setMessage("Image uploaded. Save the draft to attach it.");setBusy(false)}
  function addStage(){const last=stages.at(-1);setStages(current=>[...current,{id:crypto.randomUUID(),stage:"new-stage",phase:"growth",position:current.length+1,day_from:(last?.day_to??0)+1,day_to:(last?.day_to??0)+1,guidance:"",next_action:"",action_interval_days:1,observation_prompt:"",what_is_happening:"",milestone:"",what_good_looks_like:"",common_problems:[],photo_check_prompt:null,harvest_ready:false,harvest_criteria:null,image:null}]);setStatus("draft")}
  return <>
    <div className="actions" style={{justifyContent:"space-between"}}><div><p className="eyebrow">Seed editor · {status}</p><h1>{seed.name}</h1></div><div className="actions"><button className="button ghost" onClick={()=>save()} disabled={busy}>Save draft</button>{["publisher","owner"].includes(role)&&<button className="button" onClick={publish} disabled={busy||!validation.valid}>Publish</button>}</div></div>
    {message&&<p className={message.includes("Fix")||message.includes("required")?"error":"notice"}>{message}</p>}
    {!validation.valid&&<div className="notice"><strong>Validation</strong><ul>{validation.errors.slice(0,8).map(error=><li key={error}>{error}</li>)}</ul></div>}
    <section className="card"><h2>Seed metadata</h2><div className="form-grid">{textFields.map(([key,label])=><div className={`field ${["description","expected_result","harvest_readiness","harvest_instructions","storage_guidance"].includes(key)?"span-2":""}`} key={key}><label>{label}</label>{["description","expected_result","harvest_readiness","harvest_instructions","storage_guidance"].includes(key)?<textarea value={seed[key]??""} onChange={e=>setField(key,e.target.value)}/>:<input value={seed[key]??""} onChange={e=>setField(key,e.target.value)}/>}</div>)}<div className="field"><label>Minimum days</label><input type="number" value={seed.duration_days_min} onChange={e=>setField("duration_days_min",Number(e.target.value))}/></div><div className="field"><label>Maximum days</label><input type="number" value={seed.duration_days_max} onChange={e=>{setField("duration_days_max",Number(e.target.value));setField("duration_days",Number(e.target.value))}}/></div><div className="field"><label>Access</label><select value={seed.access_type} onChange={e=>setField("access_type",e.target.value)}><option value="free">Free</option><option value="paid">Paid</option><option value="coming_soon">Coming soon</option></select></div><div className="field"><label>Review</label><select value={seed.content_review_status} onChange={e=>setField("content_review_status",e.target.value)}><option value="draft">Draft</option><option value="grower_reviewed">Grower reviewed</option></select></div><div className="field span-2"><label>Materials, one per line</label><textarea value={(seed.materials??[]).join("\n")} onChange={e=>setField("materials",e.target.value.split("\n").filter(Boolean))}/></div><div className="field span-2"><label>Sources, one URL per line</label><textarea value={(seed.content_sources??[]).join("\n")} onChange={e=>setField("content_sources",e.target.value.split("\n").filter(Boolean))}/></div></div></section>
    <section className="card" style={{marginTop:22}}><h2>Seed images</h2><input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/><p>{(seed.images??[]).length} image reference(s). CMS uploads are public catalogue assets. User photos use a separate private bucket.</p></section>
    <section className="card" style={{marginTop:22}}><p className="eyebrow">Mobile preview</p><h2 style={{color:"var(--forest)"}}>{seed.name}</h2><p><em>{seed.botanical_name}</em></p><p>{seed.description}</p><div className="actions"><span className="pill">{seed.duration_days_min} to {seed.duration_days_max} days</span><span className="pill">{seed.difficulty_label}</span><span className="pill">{seed.access_type}</span></div><p style={{marginTop:18}}><strong>{stages.length} authored stages</strong>, first action: {stages[0]?.next_action??"Not set"}</p></section>
    <div className="actions" style={{justifyContent:"space-between",marginTop:30}}><h2>Growth stages</h2><button className="button secondary" onClick={addStage}>Add stage</button></div>
    {stages.map((stage,index)=><section className="card stage" key={stage.id??index}><div className="actions" style={{justifyContent:"space-between"}}><h3>Stage {index+1}: {stage.stage}</h3><button className="button ghost" onClick={()=>setStages(current=>current.filter((_,i)=>i!==index).map((item,i)=>({...item,position:i+1})))}>Remove</button></div><div className="form-grid"><div className="field"><label>Stage key</label><input value={stage.stage} onChange={e=>setStage(index,"stage",e.target.value)}/></div><div className="field"><label>Phase</label><select value={stage.phase} onChange={e=>setStage(index,"phase",e.target.value)}><option value="setup">Setup</option><option value="growth">Growth</option><option value="harvest">Harvest</option></select></div><div className="field"><label>From day</label><input type="number" value={stage.day_from} onChange={e=>setStage(index,"day_from",Number(e.target.value))}/></div><div className="field"><label>To day</label><input type="number" value={stage.day_to??""} onChange={e=>setStage(index,"day_to",e.target.value?Number(e.target.value):null)}/></div>{[["next_action","Next action"],["guidance","Guidance"],["observation_prompt","Observation prompt"],["what_is_happening","What is happening"],["milestone","Milestone"],["what_good_looks_like","What good looks like"],["photo_check_prompt","Photo prompt"]].map(([key,label])=><div className="field span-2" key={key}><label>{label}</label><textarea value={stage[key]??""} onChange={e=>setStage(index,key,e.target.value||null)}/></div>)}<div className="field span-2"><label>Common problems, one per line</label><textarea value={(stage.common_problems??[]).join("\n")} onChange={e=>setStage(index,"common_problems",e.target.value.split("\n").filter(Boolean))}/></div><label><input type="checkbox" checked={Boolean(stage.harvest_ready)} onChange={e=>setStage(index,"harvest_ready",e.target.checked)}/> Harvest-ready stage</label></div></section>)}
  </>
}
