const palette = {
  background: "#EEECE7",
  raised: "#F3F1EC",
  brand: "#472C2A",
  olive: "#6D7A38",
  seed: "#504B24",
  accent: "#A66C6F",
  progressText: "#6A6960",
  highlight: "#70484A",
  coachLabel: "#DCDAD5",
  tabActiveSurface: "#DCDAD5",
  tabInactiveSurface: "#E5E3DE",
  tabActiveContent: "#846967",
  alert: "#A64032"
} as const;

export const colors = {
  ...palette,
  olivePressed: "#5E692F",
  track: "rgba(80,75,36,0.16)",
  textStrong: "rgba(71,44,42,0.90)",
  textSecondary: "rgba(71,44,42,0.78)",
  textMuted: "rgba(71,44,42,0.62)",
  textFaint: "rgba(71,44,42,0.32)",
  border: "rgba(71,44,42,0.10)",
  borderSoft: "rgba(71,44,42,0.06)",
  field: "#FFFDF9",
  harvestBackground: palette.seed,
  harvestPanel: "#34340F",

  // Compatibility names remain while older screens move to the semantic names
  // above. Every value comes from the approved 2026 palette.
  canvas: palette.background,
  card: palette.raised,
  sand: palette.tabInactiveSurface,
  photoA: palette.tabInactiveSurface,
  photoB: palette.tabInactiveSurface,
  tabActiveA: palette.tabActiveSurface,
  tabActiveB: palette.tabActiveSurface,
  gaugeTrack: "rgba(80,75,36,0.16)",
  input: "#FFFDF9",
  terracotta: palette.accent,
  terracottaText: palette.brand,
  terracottaPanel: palette.highlight,
  sage: palette.olive,
  forest: palette.seed,
  forestPressed: "#5E692F",
  forest75: "rgba(80,75,36,0.75)",
  stone: palette.raised,
  ink: palette.brand,
  ink90: "rgba(71,44,42,0.90)",
  ink82: "rgba(71,44,42,0.78)",
  ink64: "rgba(71,44,42,0.62)",
  ink34: "rgba(71,44,42,0.32)",
  oliveLabel: palette.olive,
  surface: palette.raised,
  surfaceMuted: palette.background,
  textPrimary: palette.brand,
  textSubtle: "rgba(71,44,42,0.62)",
  actionPrimary: palette.olive,
  actionPrimaryText: palette.raised,
  actionSecondary: palette.raised,
  actionSecondaryText: palette.olive,
  statusSuccess: palette.olive,
  statusSuccessSurface: palette.raised,
  statusAttention: palette.alert,
  statusAttentionSurface: palette.raised
} as const;
